version: "3"
services:
  backend:
    build:
      context: backend
    image: tatou/backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - tatou-backend-network
    env_file:
      - env/backend.env
    restart: always
  
  frontend:
    build:
      context: frontend
    image: tatou/frontend:latest
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
      - tatou-frontend-volume:/app/node_modules
    networks:
      - tatou-frontend-network
    env_file:
      - env/frontend.env
    restart: always
    
volumes:
  tatou-frontend-volume:

networks:
  tatou-frontend-network:
  tatou-backend-network: